== Users and Groups
You can manage users and groups in Red Hat SSO, and also import from different feredration providers e.g. LDAP and Kerberos. In this lab we only use the User, groups function provided with Red Hat SSO, and wont be importing from LDAP or Kerberos. However bare in mind that most of the customers would have an internal directory server where the users are stored. And Red Hat SSO can easily connect with them.

Red Hat SSO has supports for both roles and groups.

Roles can be added realm-wide or to specific applications. There is also support for composite roles where a role can be a composite of other roles. This allows for instance creating a default role that can be added to all users, but in turn easily managing what roles all the users with the default role will have.

Groups have a parent/child relationship where a child inherits from its parent. Groups can be mapped to roles, have attributes or just added directly to the token for your application to resolve its meaning.

Let's start by creating a role and see it in the token.

- Open the Red Hat SSO Admin Console.

- Click on Roles and Add Role. 

- Set the Role Name to User and click `Save.

- Now click on Users and find the user you want to login with. 

- Click on Role Mappings. Select user from Available roles and click Add selected.

- Go back to the JS Console and click Refresh, then Access Token JSON. 

[source, json]
----
  
  "realm_access": {
    "roles": [
      "User",
      "offline_access",
      "uma_authorization"
    ]
  }
----

Refresh your js-console and notice that there is a `realm_access` claim in the token that now contains the user role.


Next let's create a Group. 
- Go back to the Red Hat SSO Admin Console. 
- Click on New and use mygroup as the Name. 
- Click on Attributes and add key user_type with value consumers.

Now let's make sure this group and the claim is added to the token. 
- Go to Client Scopes and click Create. 
- For the name use myscope. 
- Click on Mappers. 
- Click on Create.

- Fill in the following values:

    Name: groups
    Mapper Type: Group Membership
    Token Claim Name: groups

- Click Save then go back to Mappers and click Create again.

- Fill in the following values:

    Name: type
    Mapper Type: User Attribute
    User Attribute: user_type
    Token Claim Name: user_type
    Claim JSON Type: String

- Find the js-console client again and add the myclaim as a default client scope.

- Finally add a user to this group, by going to the `Users`; 

- Find your user and add group to it. 

- When you login to the JS Console you will be able to see the claim.

- Go back to the JS Console and click Refresh, then Access Token JSON. Notice that there is a groups claim in the token as well as a user_type claim.

[source, json]
----
  
  "scope": "openid avatar myscope profile email",
  "user_type": "consumers",
  "Group Membership": [
    "/mygroup"
  ]
----

Congratulations now you have created a user, added them to a group. 
We have added claims both via user and via groups. 
Lets move on and add an Identity Provider in the next section.