== Identity providers


=== OAUTH and OAUTH2
Lets say you are running an e-commerce shop online. And today you have a couple of million users. Business is growing. Now you are being approached by third-party application developers to integrate with your services; Lets assume they are running a chat service or a gaming platform, they would like to provide services to your customer and thiers. Also brining in new business. How can we handle such an integration?

OAuth is a way to get access to protected data from an application. It's safer and more secure than asking users to log in with passwords. OAuth will also allow developers to securely get the user data. So is OAuth an Authentication mechanism? No its not. OAuth provides the framework to securely access that data. So OAuth asks for a token and gets it. For Authentication you would use Open ID Connect or SAML etc. So rather then sharing passwords between services OAuth is te protocol that helps brings the whole RESTful web together. Similar to when one uses Google or Githhub login to use other services from like e.g. Red Hat developer

=== Users from Github
Now that we have users in Red Hat SSO as well as loading users from LDAP let's get users from an external Identity Provider. For simplicity we'll use GitHub, but the same approach works for a corporate identity provider and other social networks.

Open the Red Hat SSO Admin Console.

Click on Identity Providers. From the drop-down select GitHub. Copy the value in Redirect URI. You'll need this in a second when you create a new OAuth application in GitHub.

In a new tab open Register a new OAuth application.

Fill in the following values:

    Application name: Keycloak
    Homepage URL:
    Authorization callback URL:

Now copy the value for Client ID and Client Secret from GitHub to the Red Hat SSO Admin Console.

We also want to add a mapper to retrieve the avatar from GitHub. Click on Mappers and Create.

Fill in the following values:

    Name: avatar
    Mapper Type: Attribute Importer
    Social Profile JSON Field Path: avatar_url
    User Attribute Name: avatar_url

Logout from the JS Console and instead of providing a username or password to login click on GitHub.

Notice how it automatically knows your name and also has your avatar.

